name: Terraform Destroy Workflow

on:
  workflow_dispatch:

env:
    AWS_REGION: eu-west-2
    TF_VERSION: "1.15.1"

permissions:
    id-token: write
    contents: read

concurrency:
    group: terraform-destroy
    cancel-in-progress: true

jobs:
    destroy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v6
          with:
            role-to-assume: ${{ secrets.OIDC_ROLE }}
            aws-region: ${{ env.AWS_REGION }}

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v4
          with:
            terraform_version: ${{ env.TF_VERSION }}

        - name: Terraform init
          working-directory: ./infra  
          run: terraform init

        - name: Terraform Destroy
          working-directory: ./infra  
          run: terraform destroy -auto-approve